apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name | dump }}
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: user:guest
  lifecycle: experimental
  projectName: ${{ values.projectName | dump }}
  moduleName: ${{ values.moduleName | dump }}
  informationAuthor: user:guest
  modality: ${{ values.modality | dump }}
  bodyParts: ${{ values.bodyParts | dump }}
  processingPurpose: ${{ values.processingPurpose | dump }}
  protocol: ${{ values.protocol | dump }}
  algorithmType: ${{ values.algorithmType | dump }}
  packageType: ${{ values.packageType | dump }}
  supportedOs: ${{ values.supportedOs | dump }}
  sourceCodeLanguage: ${{ values.sourceCodeLanguage | dump }}
  developmentStatus: ${{ values.developmentStatus | dump }}
  linkToProjectPage: ${{ values.linkToProjectPage | dump }}